-- liquibase formatted sql

-- changeset hung.hv:1-create-users-table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  turns INTEGER NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT uk_users_email UNIQUE (email),
  CONSTRAINT chk_users_score_non_negative CHECK (score >= 0),
  CONSTRAINT chk_users_turns_non_negative CHECK (turns >= 0)
);

CREATE INDEX idx_users_score_id ON users(score DESC, id ASC);

-- changeset hung.hv:2-create-payment-transactions-table
CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_session_id VARCHAR(255) NOT NULL,
    checkout_url VARCHAR(2048) NOT NULL,
    status VARCHAR(32) NOT NULL,
    turns INT NOT NULL,
    amount BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payment_transactions_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_payment_transactions_provider_session UNIQUE (provider_session_id)
);

CREATE INDEX idx_payment_transactions_user_status ON payment_transactions(user_id, status);

-- changeset hung.hv:3-create-refresh-tokens-table
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
