# Database connection properties
url=${DB_URL}
username=${DB_USERNAME}
password=${DB_PASSWORD}
driver=org.postgresql.Driver

# Liquibase configuration
changeLogFile=db/changelog/master.xml

# Optional settings
logLevel=DEBUG
